defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: default

title: Model Counting Competition MC 2020
# subtitle: Full-Stack Developer

baseurl: "mc_test"
url: ""

# Side Menu Links
menu:
  - text: News
    link: /news
    icon: ""

  - text: Organization
    link: /
    icon: ""

  - text: Competition Tracks
    link: /model-counting-competition
    icon: ""

  - text: Submission & Important Dates
    link: /dates
    icon: ""

# Socialmedia Icons
social_icons:
  - name: linkedin
    # link: https://www.linkedin.com/christianezeani
    icon: fab fa-linkedin

  - name: github
    # link: https://github.com/christianezeani
    icon: fab fa-github-square

  # - name: facebook
  #   link: https://www.facebook.com/christian.ezeani.cyb
  #   icon: fab fa-facebook-square

  - name: twitter
    # link: https://www.twitter.com/christianezeani
    icon: fab fa-twitter


    
