defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: default

title: Model Counting
email: daajoe@users.noreply.github.com
description: >-
  Model Counting
tagline: Since 2020

#theme: panthera-jekyll

baseurl: ""
url: ""

# Side Menu Links
menu:
  - text: News
    link: /news
    icon: ""
    #TODO: Newsletter

  - text: About
    link: /about
    icon: ""

  - text: Past Iterations
    link: /past_iterations
    icon: ""

  - text: Solvers
    link: /solvers/solvers
    icon: ""

  - text: Competition 2023
    link: /2023/mc_description
    icon: ""

  - text: Workshop 2023
    link: /2023/mcw_description
    icon: ""

  - text: Submission &<br>Important Dates
    link: /2023/dates
    icon: ""

#  - text: Program
#    link: /2020/mcw_program
#    icon: ""

left_side:
  background_image: "./assets/images/left-background.jpg"

# Socialmedia Icons
social_icons:
#  - name: rssfeed
#    link: https://mccompetition.org/feed.xml
#    icon: fab fa-rssfeed

  - name: github
    link: https://github.com/daajoe/mccompetition.org
    icon: fab fa-github-square

  - name: twitter
    link: https://www.twitter.com/joedaa
    icon: fab fa-twitter



    
