defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: default

title: Model Counting
email: daajoe@users.noreply.github.com
description: >-
  Model Counting
tagline: Since 2020

baseurl: ""
url: ""

# Side Menu Links
menu:
  - text: News
    link: /news
    icon: ""
    #TODO: Newsletter

#  - text: About
#    link: /2020/about
#    icon: ""

  - text: Competition<br> (MC 2020)
    link: /2020/mc_description
    icon: ""

  - text: Workshop<br> (MCW 2020)
    link: /2020/mcw_description
    icon: ""

  - text: Submission &<br>Important Dates
    link: /2020/dates
    icon: ""

  - text: Program
    link: /2020/mcw_program
    icon: ""


# Socialmedia Icons
social_icons:
#  - name: rssfeed
#    link: https://mccompetition.org/feed.xml
#    icon: fab fa-rssfeed

  - name: github
    link: https://github.com/daajoe/mccompetition.org
    icon: fab fa-github-square

#  - name: twitter
    # link: https://www.twitter.com/christianezeani
#    icon: fab fa-twitter


    
